# Generated by Django 4.1.2 on 2022-10-27 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_extrato_alter_conta_valor'),
    ]

    operations = [
        migrations.AddField(
            model_name='extrato',
            name='tipo_transacao',
            field=models.TextField(blank=True, verbose_name='Tipo transação'),
        ),
    ]
